---
- name: install nginx and php5
  hosts: localhost

  tasks:
    - name: install nginx
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - nginx

    - name: configure nginx
      copy: src={{ item.src }} dest={{ item.dest }} mode="0755"
      with_items:
        - { src: '~/ansible/config/nginx.conf', dest: '/etc/nginx/nginx.conf' }

    - name: install php
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - php5-common
        - php5-cli
        - php5-fpm
        - php-apc
        - php5-mysql

    - name: configure php
      lineinfile: dest={{ item.dest }} regexp='{{ item.regexp }}' line='{{ item.line }}' backrefs=yes
      with_items:
        - { dest: '/etc/php5/fpm/php.ini', regexp: '(\s*);+cgi\.fix_pathinfo\s*=\s*1', line: '\1cgi.fix_pathinfo = 0' }
        - { dest: '/etc/php5/fpm/php.ini', regexp: '(\s*)upload_max_filesize\s*=\s*2M', line: '\1upload_max_filesize = 32M' }
        - { dest: '/etc/php5/fpm/php.ini', regexp: '(\s*)post_max_size\s*=\s*8M', line: '\1post_max_size = 64M' }
        - { dest: '/etc/php5/fpm/php-fpm.conf', regexp: '(\s*);+daemonize\s*=\s*yes', line: '\1daemonize = no' }

    - name: prepare runit
      file: path={{ item.path }} state=directory mode="0755"
      with_items:
        - { path: '/etc/service/phpfpm' }
        - { path: '/etc/service/nginx' }

    - name: setup runit
      copy: src={{ item.src }} dest={{ item.dest }} mode="0755"
      with_items:
        - { src: 'service/phpfpm.sh', dest: '/etc/service/phpfpm/run' }
        - { src: 'service/nginx.sh',  dest: '/etc/service/nginx/run' }

    - name: apt-get clean
      shell: apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
